### ISSUE TITLE
Respond to ping event

### ISSUE THREAD

**Issue by kumy** [logsol/Github-Auto-Deploy#26]
when creating a new hook on Github, a ping event is sent.
Having a response of HTTP 204 would allow a green mark on the sent event.

**Comment by crash7** [comment]
+1

**Comment by nimer-** [comment]
Simple fix 'til authors update script https://github.com/logsol/Github-Auto-Deploy/blob/master/GitAutoDeploy.py#L37-38

(If going to edit it, don't forget to use spaces for indent - otherwise it wont work). 

I hope it helps ;)

```
    def do_POST(self):
        if self.headers.getheader('x-github-event') == 'ping':
            self.respond(204)
            return
			
        if (self.headers.getheader('x-github-event') != 'push') or (self.headers.getheader(x-github-event) !='ping'):
```
